### ISSUE TITLE
Pandoc's `span` classes (tokens) are too simplistic

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/anki#152]
> For example, `.fu` class styles a lot more elements than a token in Visual Studio Code does.
> This makes it incredibly difficult (impossible) to recreate someone's theme with Pandoc's Skylighting.
> **We're using [Breeze Dark Theme](https://marketplace.visualstudio.com/items?itemName=AndrewFridley.Breeze-Dark-Theme) plugin for Visual Studio Code as an example.**

- [ ] #145 (possible fix, but requires Python)

#### Coloured brackets are not possible

<img width="192" alt="coloured-brackets-are-impossible-01" src="https://github.com/user-attachments/assets/faa5d510-9a49-4bf2-b0aa-9ccb2631d89b">
<img width="147" alt="coloured-brackets-are-impossible-02" src="https://github.com/user-attachments/assets/1c6fc325-2eeb-4d98-9f90-97c79167069f">

#### Different colours for `functions()` and `function(arguments)` are not possible

<img width="605" alt="model-div-span-01-correct-colours" src="https://github.com/user-attachments/assets/259df5be-c75e-44ab-bc77-bb9e5763c6c5">
<img width="445" alt="model-div-span-02" src="https://github.com/user-attachments/assets/04ef81cc-a390-42ab-a910-fb09a85dc855">
<img width="595" alt="model-div-span-03" src="https://github.com/user-attachments/assets/4064dcc4-8dee-4778-94ec-1b35c7b874ff">

#### `.op` (Operator class) is not nuanced enough (compared with VSC)

<img width="602" alt="operator-class-00" src="https://github.com/user-attachments/assets/c3fb7c9d-4d44-4fef-b30a-55d3fce22ae5">
<img width="409" alt="operator-class-01" src="https://github.com/user-attachments/assets/d55921c7-eca4-44b6-97c2-279e313c6fd6">
<img width="592" alt="operator-class-02" src="https://github.com/user-attachments/assets/46d1f810-7a45-4017-ac87-f1cda4950390">

#### `.dv` (Decimal Value) used for CSS values. Doesn't seem right?

<img width="1088" alt="decimal-value-for-css-values-for-fuck-sake" src="https://github.com/user-attachments/assets/8a2b2c29-1f77-4fca-88db-150c92957b7a">

#### Comments are not differentiated in Pandoc?

<img width="632" alt="comments-aren't-differentiated-as-much?-01" src="https://github.com/user-attachments/assets/d2044bfa-7094-49e1-9ed2-f4365332bacd">
<img width="1109" alt="comments-aren't-differentiated-as-much?-02" src="https://github.com/user-attachments/assets/d04b47e6-7481-4c94-a108-5613733547d3">

#### `.dt` are shared across different language types, meaning you've got to take care making decisions about color.

<img width="892" alt="ugh-is-also-a- dt(datatype)-02" src="https://github.com/user-attachments/assets/c8099c26-c8fb-443b-91b5-0cd73b5acaec">
<img width="891" alt="ugh-is-also-a- dt(datatype)-so-hard-to-change" src="https://github.com/user-attachments/assets/97c4abbc-61ed-4bb1-8171-17e213ca3901">

**Comment by badlydrawnrob** [comment]
> ORIGINAL PROBLEM with Pandoc's Skylighting package ...

For example, `.fu` class styles a lot more elements than a token in Visual Studio Code does.

- This makes it incredibly difficult (impossible) to recreate someone's theme with Pandoc's Skylighting.
- **We're using [Breeze Dark Theme](https://marketplace.visualstudio.com/items?itemName=AndrewFridley.Breeze-Dark-Theme) plugin for Visual Studio Code as an example.**
- I've [logged an issue](https://github.com/jgm/pandoc/discussions/10115) with Pandoc and it seems like something I _might_ be able to change myself

Other links below:

- [ ] #145 (interesting fix with [pygments](https://pygments.org/docs/cmdline/), but might not be a huge improvement)[^1]
- [ ] #134 More examples of the issue (with Monokai theme)

The below issues are some of the problems we have to face creating a nice syntax highlighting theme, or modifying one. It's by no means exhaustive, but in an ideal world, these issues would be fixed!

### Some things are impossible

#### Different colours for `functions()` and `function(arguments)` are not possible

<img width="605" alt="model-div-span-01-correct-colours" src="https://github.com/user-attachments/assets/259df5be-c75e-44ab-bc77-bb9e5763c6c5">
<img width="445" alt="model-div-span-02" src="https://github.com/user-attachments/assets/04ef81cc-a390-42ab-a910-fb09a85dc855">
<img width="595" alt="model-div-span-03" src="https://github.com/user-attachments/assets/4064dcc4-8dee-4778-94ec-1b35c7b874ff">

#### Coloured brackets are not possible

<img width="192" alt="coloured-brackets-are-impossible-01" src="https://github.com/user-attachments/assets/faa5d510-9a49-4bf2-b0aa-9ccb2631d89b">
<img width="147" alt="coloured-brackets-are-impossible-02" src="https://github.com/user-attachments/assets/1c6fc325-2eeb-4d98-9f90-97c79167069f">

#### `.op` (Operator class) is not nuanced enough (compared with VSC)

<img width="602" alt="operator-class-00" src="https://github.com/user-attachments/assets/c3fb7c9d-4d44-4fef-b30a-55d3fce22ae5">
<img width="409" alt="operator-class-01" src="https://github.com/user-attachments/assets/d55921c7-eca4-44b6-97c2-279e313c6fd6">
<img width="592" alt="operator-class-02" src="https://github.com/user-attachments/assets/46d1f810-7a45-4017-ac87-f1cda4950390">


### Some things feel wrong?

#### `in` (`.kw` keyword) looks outside of the `.cf` (control flow) and doesn't feel right (should be same colour as `for`)

<img width="668" height="598" alt="Image" src="https://github.com/user-attachments/assets/01404493-592d-4f37-8dce-61794c6c79e4" />

#### `.dv` (Decimal Value) used for CSS values. Doesn't seem right?

<img width="1088" alt="decimal-value-for-css-values-for-fuck-sake" src="https://github.com/user-attachments/assets/8a2b2c29-1f77-4fca-88db-150c92957b7a">


### Some things are difficult

#### Comments are not differentiated in Pandoc?

<img width="632" alt="comments-aren't-differentiated-as-much?-01" src="https://github.com/user-attachments/assets/d2044bfa-7094-49e1-9ed2-f4365332bacd">
<img width="1109" alt="comments-aren't-differentiated-as-much?-02" src="https://github.com/user-attachments/assets/d04b47e6-7481-4c94-a108-5613733547d3">

#### `.dt` are shared across different language types, meaning you've got to take care making decisions about color.

<img width="892" alt="ugh-is-also-a- dt(datatype)-02" src="https://github.com/user-attachments/assets/c8099c26-c8fb-443b-91b5-0cd73b5acaec">
<img width="891" alt="ugh-is-also-a- dt(datatype)-so-hard-to-change" src="https://github.com/user-attachments/assets/97c4abbc-61ed-4bb1-8171-17e213ca3901">

[^1]: We've already travelled this road before. Trying to [hack javascript](https://github.com/badlydrawnrob/anki/issues/19) to make `highlight.js` work, exploring [Pygments or add-ons](https://github.com/badlydrawnrob/anki/issues/21) to extend our flashcards, and lots of other [little problems](https://github.com/badlydrawnrob/anki/issues/33) that make our life more complicated. Pandoc is the easiest of the bunch, but comes with tradeoffs.
