### ISSUE TITLE
Install and build documentation (beginner and advanced)

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/anki#54]
> **Simplify this issue down to a single paragraph!!**
>
> Change terminology for documentation to `easy` and `hard` (`so-so` isn't very helpful)

- [ ]  #42 (A simple [update guide](https://github.com/badlydrawnrob/anki/releases/tag/2.5.0) like the release)
- [x] #97
- [ ] **Simplify initial README** so it's easier to digest
     - **Show it, don't say it?** Add some gifs like below
     - User pain points. i.e: **[install without breaking things](https://github.com/badlydrawnrob/anki/issues/42)**.
     - [ ] **Update the professional docs**
- [ ] #104
- [ ] #55 **Build folder and basic `npm` scripts explained in a very simple way**
    - Most of the [build stuff in print-first-css](https://github.com/badlydrawnrob/print-first-css/issues/25) can be hidden
    - Like a module, some bits are hidden and not extendable.
    - **Remember [the problems with `print-first-css`](https://github.com/badlydrawnrob/anki/issues/54#issuecomment-1830872091) and npm with GitHub repos!**
- [ ] **Other `package.json` related issues**
    - #102 
    - #96 
- [ ] #71
- [ ] **Issues should probably be handled better**
    - Simple enough to not scare kids off
    - Yet thorough enough for my own purposes ...
    - Nice example of a [gitbot issue auto-responder](https://github.com/elm/compiler/issues/2258)

## Already thought about ...

- [x] **[Build script and security notes](https://github.com/badlydrawnrob/print-first-css/issues/25)** (Pandoc, Less CSS, [Print First CSS](https://github.com/badlydrawnrob/print-first-css))
    - [ ] [Build passing](https://github.com/dwyl/repo-badges) and other shields (thanks @callmemarcleo)
    - [x] Using [semantic versioning](https://medium.com/fiverr-engineering/major-minor-patch-a5298e2e1798) properly
    - [x] <s>Be very careful about [mustache and JSON formatting](https://github.com/badlydrawnrob/anki/issues/54#issuecomment-1837240323) using the demo files — especially things like [the `{{cloze:tag}}` demo](https://github.com/badlydrawnrob/anki/issues/49)</s>
    - [x] <s>Demo is useful for now, but involves copying (and slightly editing) the main Card themes in `source/themes/demo/...`</s>
- [x] **Saner internal links?** (rather than them scattered in various places)
    - [x] **You can actually hover over a link** in [Visual Studio Code](https://learn.microsoft.com/en-us/visualstudio/ide/reference/how-to-display-urls-as-links-in-the-editor?view=vs-2022) (see below)
    - [x] <s>**[An online tool](https://dnschecker.org/website-broken-link-checker.php)** (it indexes all Github's links too, not just the README ☹️)</s>
    - [ ] ❓<s>Using a [link checker tool](https://brettterpstra.com/2021/02/08/linkchecker-a-bookmarklet-for-web-writers/) (Marked App only checks external links)</s>
    - [ ] <s>💩 <s>Or a [CLI tool](https://tinyurl.com/yr7py3sr)</s> (too many depencies / a ballache to set up)</s>
- [x] <s>Generate PDF</s>

<img width="596" alt="Screenshot 2023-12-01 at 21 31 24" src="https://github.com/badlydrawnrob/anki/assets/1176875/5bc99f31-965b-40f2-83e0-55959e080731">

_🏆 **<key>cmd ⌘ + click</key>:** Turns the link blue and takes you to the correct `.md` page!_

<img width="448" alt="Screenshot 2023-12-01 at 18 30 35" src="https://github.com/badlydrawnrob/anki/assets/1176875/1a92ff60-3c52-494e-b2bc-95ec58114285">

_<s>**Use a CLI tool:**</s> 34 bloody dependencies to check your links_

https://github.com/badlydrawnrob/anki/assets/1176875/e3813b95-0f4f-439e-ae7c-0c41f7ab36e1

_Create a gif how to video with [this convertor](https://cloudconvert.com/mov-to-gif)_

**Comment by badlydrawnrob** [comment]
I removed this for now [from the advanced docs](https://github.com/badlydrawnrob/anki/blob/master/source/docs/advanced/index.md) but may need to put it back in if people are struggling with dependancies:

> 5. `npm update print-first-css`<sup>¶</sup>
> 6. `npm update <package>` if necessary
>
> ¶: Sometimes [`print-first-css` doesn't update properly](https://github.com/badlydrawnrob/anki/issues/65), so make sure to `npm update print-first-css`. You might also have to [`npm audit`](https://docs.npmjs.com/cli/v10/commands/npm-audit) and `npm audit fix` to make sure dependencies have no errors. Follow the prompts.

**Comment by badlydrawnrob** [comment]
With mustache, you need to make sure that the `.json` file is formatted correctly. For basic html, you don't need to escape the JSON — however, as soon as you have HTML tags that have `" "` double quotes, you'll need to escape that value or else it will throw the following error:

<img width="560" alt="Screenshot 2023-12-02 at 19 34 44" src="https://github.com/badlydrawnrob/anki/assets/1176875/e883e456-b2e7-4d7d-afc2-c7b70346fc32">

Use [a tool like this one](https://www.freeformatter.com/json-escape.html) to escape the JSON value.

<img width="668" alt="Screenshot 2023-12-02 at 19 51 27" src="https://github.com/badlydrawnrob/anki/assets/1176875/e39f5d2c-3a48-4256-99d8-5984cc008bf2">

Furthermore, **[Anki expects `{{ ... }}` double quotes only](https://github.com/badlydrawnrob/anki/issues/56)**. Mustache allows for `{{{ ... }}}` triple quotes, or `{{& ... }}` symbol to make sure that the value DOES NOT GET ESCAPED!

**So for the time being, I've copied the front and back templates into a `demo/` folder which will handle the mustache templates and `.json`.** I may rip this out completely but it's a bit useful for now.

Without the `{{{ triple brackets }}}`, you'll see a mess of a result:

<img width="297" alt="Screenshot 2023-12-02 at 19 31 22" src="https://github.com/badlydrawnrob/anki/assets/1176875/8c5dae91-7de6-4e7d-8563-7cdd34e6e39d">
<img width="787" alt="Screenshot 2023-12-02 at 19 31 49" src="https://github.com/badlydrawnrob/anki/assets/1176875/460d0290-28b5-4932-9596-b3de0091387e">

**Comment by badlydrawnrob** [comment]
This is all too overthinky. Keep your target audience and beginners and intermediates and that'll help you scope out what you should be doing. Very, very simple compiler and mostly what you see is what you get. The advanced guys should be able to do it alone anyways.
