### ISSUE TITLE
Fix some minor css issues

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/anki#81]
> Add useful CSS to [this gist](https://gist.github.com/badlydrawnrob/5749f24c14ea4c381390f3cbbe3e16db)
>
> Some minor changes with `font-size` and possibly additional styles for [Markdown checkboxes](https://github.com/badlydrawnrob/anki/issues/40#issuecomment-1869606908). I'm using some edits of the original [Print First CSS](https://github.com/badlydrawnrob/print-first-css) due to `Verdana` font being a bit too big at default `--font-size`.
>
> **Note:** make sure [`rem`](https://snook.ca/archives/html_and_css/font-size-with-rem) is behaving properly (i.e. not inflating the font size with child elements)

### Some very old CSS changes

- [x] #23

## `code block`s

> Some way to quickly spot a piece of code we're talking about (like the cloze deletion css)
> It shouldn't be difficult to add (**searching for a specific line of code once compiled is too slow**)
>
> **[Some rough tests here](https://codepen.io/testuser-247585903/full/MWxVvzp)**

- [x] #132 (duplicate #131) (write it manually, don't use the button)
- [x] #130
- [x] #125
- [x] #129

Other things:

- [x] Make `code block` smaller `--font-size` when viewed in AnkiMobile? (There's a lot of scrolling involved)
- [ ] #121
- [x] **[Wrap inline code](https://github.com/badlydrawnrob/anki/issues/118)** so it doesn't break layout
- [ ] #66
    - [ ] Scrap `img` inside code block?
    - [ ] It can be useful for speed (take a snapshot and use that)

## New functionality?

- [ ] #40 (multiple choice)
    - [ ] Style checkboxes
    - [x] To look like
    - [ ] Multiple choice 

## Back to the start ... priority changes

- [x] **[Testing with `rem` sizing and cascade](https://codepen.io/testuser-247585903/pen/ExMPgea)** (Codepen)
- [x] **Make sure that header `code` [is large](https://github.com/badlydrawnrob/anki/issues/81#issuecomment-1891052770)!**[^1]
    - [x] **But not _too_ large!** — [Card data is taking some styles](https://github.com/badlydrawnrob/anki/issues/81#issuecomment-1902267972) from Pandoc's default
- [x] **The Notes section** (some edits)
    - Just [make the notes section](https://github.com/badlydrawnrob/anki/issues/81#issuecomment-1896263092) left-aligned? (looks neater)
    - [Add some styling](https://github.com/badlydrawnrob/anki/issues/81#issuecomment-1902643513) to inline `<code>` [such as this](https://www.clairecodes.com/blog/2018-03-16-styling-inline-code-tags/)

## Some not-so-essential changes

- [x] We have `<i>` and `<b>` but there's also [`<mark>`](https://www.scaler.com/topics/css-highlight-text/#)

## Some `rem` tests

> **`rem` only calculates [from the default `font-size`](https://www.sitepoint.com/understanding-and-using-rem-units-in-css/)**  which is set in `:root` (the `--font-size` variables are set in `print-first-css` (or override in `anki themes`) @ `style/modules/variables/typography.less`. **Tested in [Codepen](https://codepen.io/testuser-247585903/pen/ExMPgea)**[^2] — more [`rem` notes](https://snook.ca/archives/html_and_css/font-size-with-rem)

| Before | After |
|--------|------|
| image | image |

![testing-rem-sizes-cascading](https://github.com/badlydrawnrob/anki/assets/1176875/61b817e3-b736-4952-9586-4dea9c8b436f)
<img width="885" alt="Screenshot 2024-01-03 at 22 34 11" src="https://github.com/badlydrawnrob/anki/assets/1176875/13919d98-4920-4b84-9363-ed9b0afb1811">
<img width="880" alt="Screenshot 2024-01-03 at 22 40 04" src="https://github.com/badlydrawnrob/anki/assets/1176875/03269b5a-9000-41d3-9627-1837b592bb53">

## More examples of `--font-size` issues:
 
<img width="367" alt="Screenshot 2023-12-24 at 22 10 46" src="https://github.com/badlydrawnrob/anki/assets/1176875/3c1ac8bf-c117-4d45-a695-1982de61dc59">
<img width="369" alt="Screenshot 2023-12-24 at 22 11 00" src="https://github.com/badlydrawnrob/anki/assets/1176875/23dfd60d-77e3-4f36-9b19-57ffb585fbe6">

[^1]: The `code` is currently doing some (slightly odd) font reduction as Verdana was too big at the root font-size.
[^2]: There is the question whether `:root` is the correct element to set the base font-size, perhaps `html` element is more appropriate, but fuck it, it seems to work fine. According [to this `root` is practically the same as `html`](https://developer.mozilla.org/en-US/docs/Web/CSS/:root)

**Comment by badlydrawnrob** [comment]
<img width="837" alt="Screenshot 2024-01-14 at 19 27 43" src="https://github.com/badlydrawnrob/anki/assets/1176875/40f96042-1720-4d48-8cf5-f94b80cdea47">

**Comment by badlydrawnrob** [comment]
<img width="707" alt="Screenshot 2024-01-17 at 17 22 05" src="https://github.com/badlydrawnrob/anki/assets/1176875/c7eae74f-d7e0-47c1-9518-b72d69e29116">

**Comment by badlydrawnrob** [comment]
<img width="899" alt="Screenshot 2024-01-20 at 21 18 49" src="https://github.com/badlydrawnrob/anki/assets/1176875/d7630232-2da6-4d47-8630-f9f155365b5b">

**Comment by badlydrawnrob** [comment]
<img width="902" alt="Screenshot 2024-01-20 at 21 42 24" src="https://github.com/badlydrawnrob/anki/assets/1176875/423053f6-06e3-4065-8542-09b7caf78d94">

**Comment by badlydrawnrob** [comment]
## Inline code isn't standout enough!

<img width="699" alt="Screenshot 2024-01-21 at 14 14 16" src="https://github.com/badlydrawnrob/anki/assets/1176875/0297787a-0ddb-495f-9417-39db3571bfda">

**Comment by badlydrawnrob** [comment]
Most of these are fixed now
